name = "Corvus Corax Mod Pack"
author = "Einar Cr0w"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f35da952f5ced73a0d43c0aa7cb5b390579dd813d507c8344beb5edf9d1fa89"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
