name = "Corvus Corax Mod Pack"
author = "Einar Cr0w"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0321d332c5e13cb5ec39303c025e7940c391e274b75b4f5f1db38fabec8588b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
packwiz-url = "https://eincr0w.github.io/corvuscorax_modpack/index.toml"
