name = "Corvus Corax Mod Pack"
author = "Einar Cr0w"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d480890224671c778c64c85d4070def0d8b2ebe84e45c72bbe2b78275ca9a7d9"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
packwiz-url = "https://eincr0w.github.io/corvuscorax_modpack/index.toml"
